### PR TITLE
Nitro Settings

### PR DESCRIPTION
**Pull request by Kagashini**
I don't know how to do it better but I know how to create crutches ;)
ZTF

### CODE REVIEW

**Comment by irusanov** [comment]
Hi,
I was thinking to add it as a single item, e.g.:
`RX/TX/Ctrl. Line    1/2/0`
or
`Nitro  1/2/0`

**Comment by Kagashini** [comment]
Nitro settings for DDR5. I don't know how this will be displayed on Phoenix.
image
It works on Gigabyte and ASUS. I don't know anyone with MSI.

**Comment by Kagashini** [comment]
8600G don't have this settings.

**Comment by irusanov** [comment]
This got implemented in the latest version, but only in the System Info dialog and the debug report. I will think about the best way to include it in the main screen, but can't make a commitment to that :) Thanks for providing the inffo again! Should hae included you in the changelog, but I didn't actually remembered where I got it from. Will do retroactively and add your name in the next changelog.

**Comment by Kagashini** [comment]
Thanks!

**Pull request closed without merging**
